import { Property } from "./types"

export const properties: Property[] = [
  // Commercial Spaces
  {
    id: "commercial-a",
    type: "commercial",
    name: "Commercial Space A",
    squareFeet: 650,
    monthlyRent: 595,
    description: "Perfect for a boutique shop, coffee bar, or professional office. Features exposed brick and large storefront windows.",
    features: ["Exposed brick", "Storefront windows", "High ceilings", "Updated utilities"],
    status: "available",
  },
  {
    id: "commercial-b",
    type: "commercial",
    name: "Commercial Space B",
    squareFeet: 1200,
    monthlyRent: 995,
    description: "Ideal for restaurants, retail, or creative studios. Spacious layout with excellent visibility.",
    features: ["Open floor plan", "Street-level access", "Updated HVAC", "Original hardwood"],
    status: "available",
  },
  {
    id: "commercial-c",
    type: "commercial",
    name: "Commercial Space C",
    squareFeet: 2100,
    monthlyRent: 1495,
    description: "Premium commercial space suitable for larger retail operations or multiple business uses.",
    features: ["Expansive layout", "Multiple entrances", "Loading access", "High foot traffic"],
    status: "available",
  },
  {
    id: "theater",
    type: "commercial",
    name: "Historic Theater",
    squareFeet: 3500,
    monthlyRent: 0, // Event space pricing varies
    description: "Beautifully restored theater space with stage, perfect for events, performances, and community gatherings.",
    features: ["Stage and backstage", "Theater seating", "Historic character", "Event-ready"],
    status: "coming_soon",
  },
  // Residential Spaces
  {
    id: "residential-1br-1",
    type: "residential",
    name: "1-Bedroom Apartment #1",
    squareFeet: 750,
    monthlyRent: 795,
    bedrooms: 1,
    description: "Charming one-bedroom with modern amenities and historic character. Downtown living at its finest.",
    features: ["Updated kitchen", "In-unit laundry", "Exposed brick", "High ceilings"],
    status: "available",
  },
  {
    id: "residential-1br-2",
    type: "residential",
    name: "1-Bedroom Apartment #2",
    squareFeet: 750,
    monthlyRent: 795,
    bedrooms: 1,
    description: "Cozy one-bedroom featuring original architectural details and contemporary finishes.",
    features: ["Updated kitchen", "In-unit laundry", "Original woodwork", "Energy efficient"],
    status: "available",
  },
  {
    id: "residential-1br-3",
    type: "residential",
    name: "1-Bedroom Apartment #3",
    squareFeet: 750,
    monthlyRent: 795,
    bedrooms: 1,
    description: "Bright one-bedroom apartment with excellent natural light and modern conveniences.",
    features: ["Large windows", "In-unit laundry", "Modern bath", "Hardwood floors"],
    status: "available",
  },
  {
    id: "residential-1br-4",
    type: "residential",
    name: "1-Bedroom Apartment #4",
    squareFeet: 750,
    monthlyRent: 795,
    bedrooms: 1,
    description: "Thoughtfully designed one-bedroom combining historic charm with modern comfort.",
    features: ["Updated kitchen", "In-unit laundry", "Walk-in closet", "Quiet location"],
    status: "available",
  },
  {
    id: "residential-2br-1",
    type: "residential",
    name: "2-Bedroom Apartment #1",
    squareFeet: 1100,
    monthlyRent: 995,
    bedrooms: 2,
    description: "Spacious two-bedroom apartment ideal for roommates or small families. Premium finishes throughout.",
    features: ["Updated kitchen", "In-unit laundry", "Two full baths", "Large living area"],
    status: "available",
  },
  {
    id: "residential-2br-2",
    type: "residential",
    name: "2-Bedroom Apartment #2",
    squareFeet: 1100,
    monthlyRent: 995,
    bedrooms: 2,
    description: "Beautiful two-bedroom with original character and all the modern amenities you need.",
    features: ["Updated kitchen", "In-unit laundry", "Master suite", "Exposed brick"],
    status: "available",
  },
]
